const translations = {
  en: {
    nav_home: "Home",
    nav_about: "About",
    nav_skills: "Why Us",
    nav_services: "Services",
    nav_portfolio: "Portfolio",
    nav_contact: "Contact",
    btn_contact: "Contact Me",
    hero_subtitle: "DIGITAL DENTAL DESIGNER",
    hero_tagline: "Turning Smiles into Digital Reality",
    hero_desc: "I create accurate and aesthetic digital smile designs using Exocad and modern digital dentistry tools.",
    btn_view_work: "View My Work →",
    stat_cases: "Cases Completed",
    stat_certified: "Certified",
    stat_digital_title: "Digital Dentistry",
    stat_passionate: "Passionate",
    featured_title: "Featured Work",
    featured_sub: "Real cases. Real results.",
    case_full_mouth: "Full Mouth Rehabilitation",
    case_smile_design: "Smile Design",
    case_veneers: "Veneers",
    case_waxup: "Wax-up",
    case_implant: "Implant Design",
    case_anterior: "Anterior Restoration",
    btn_all_cases: "View All Cases →",
    why_title: "Why Work With Me?",
    why_acc_title: "Accuracy",
    why_acc_desc: "Precision in every detail with digital workflow.",
    why_aes_title: "Aesthetic Results",
    why_aes_desc: "Natural and functional smile designs.",
    why_tool_title: "Modern Tools",
    why_tool_desc: "Exocad & advanced digital technology.",
    why_time_title: "On-Time Delivery",
    why_time_desc: "Committed to quality and deadlines.",
    about_title: "About Me",
    about_sub: "Get to know me better",
    about_role: "Digital Dental Designer | Trainer",
    about_p1: "I am a digital dental designer with a strong passion for creating functional and aesthetic smiles using digital technologies. I specialize in Exocad and modern digital dentistry solutions, with a focus on accuracy, detail and patient satisfaction.",
    about_p2: "I have completed 2000+ cases and continue to improve my skills through continuous learning and hands-on experience.",
    about_training: "Training",
    about_edu: "& Education",
    quote_text: '"Good design is not just about how it looks, but how it functions and makes a difference."',
    portfolio_title: "My Portfolio",
    portfolio_sub: "Selected cases from my digital dentistry work.",
    filter_all: "All",
    filter_ba: "Before / After",
    filter_sd: "Smile Design",
    filter_ven: "Veneers",
    filter_wax: "Wax-up",
    btn_more_cases: "View More Cases →",
    services_title: "My Services",
    services_sub: "Digital solutions for better smiles.",
    srv_smile_desc: "Digital smile design for natural and aesthetic results.",
    srv_exocad_title: "Exocad Design",
    srv_exocad_desc: "Full digital workflow using Exocad software.",
    srv_wax_desc: "Functional and aesthetic wax-up design.",
    srv_ven_title: "Veneers Design",
    srv_ven_desc: "Custom veneers for perfect smiles.",
    srv_imp_desc: "Implant planning and digital guides.",
    srv_arch_title: "Full Arch",
    srv_arch_desc: "Digital design for full arch rehabilitation.",
    contact_title: "Get In Touch",
    contact_sub: "Let's create something great together.",
    chat_me: "Chat with me",
    send_email: "Send Email",
    social_media: "Social Media",
    form_name: "Your Name",
    form_email: "Email Address",
    form_msg: "Message",
    form_send: "Send Message →"
  },
  ar: {
    nav_home: "الرئيسية",
    nav_about: "من أنا",
    nav_skills: "لماذا نحن",
    nav_services: "الخدمات",
    nav_portfolio: "الأعمال",
    nav_contact: "تواصل معي",
    btn_contact: "تواصل معي",
    hero_subtitle: "مصمم أسنان رقمي",
    hero_tagline: "تحويل الابتسامات إلى واقع رقمي",
    hero_desc: "أقوم بإنشاء تصاميم ابتسامة رقمية دقيقة وجمالية باستخدام برنامج Exocad وأحدث أدوات طب الأسنان الرقمي.",
    btn_view_work: "عرض أعمالي ←",
    stat_cases: "حالة مكتملة",
    stat_certified: "معتمد",
    stat_digital_title: "طب الأسنان الرقمي",
    stat_passionate: "شغف وإتقان",
    featured_title: "أبرز الأعمال",
    featured_sub: "حالات حقيقية. نتائج ملموسة.",
    case_full_mouth: "إعادة تأهيل الفك الكامل",
    case_smile_design: "تصميم الابتسامة",
    case_veneers: "فينير / عدسات",
    case_waxup: "واكس أب رقمي",
    case_implant: "تصميم زراعة الأسنان",
    case_anterior: "ترميم الأسنان الأمامية",
    btn_all_cases: "عرض جميع الحالات ←",
    why_title: "لماذا تعمل معي؟",
    why_acc_title: "الدقة العالية",
    why_acc_desc: "اهتمام بأدق التفاصيل من خلال خطة عمل رقمية.",
    why_aes_title: "نتائج جمالية",
    why_aes_desc: "تصاميم ابتسامة طبيعية ووظيفية.",
    why_tool_title: "أدوات حديثة",
    why_tool_desc: "برنامج Exocad وأحدث تقنيات طب الأسنان.",
    why_time_title: "الالتزام بالمواعيد",
    why_time_desc: "التزام تام بالجودة ومواعيد التسليم.",
    about_title: "من أنا",
    about_sub: "تعرف عليّ عن قرب",
    about_role: "مصمم أسنان رقمي | مدرب معتمد",
    about_p1: "أنا مصمم أسنان رقمي لدي شغف كبير بإيجاد ابتسامات جميلة ووظيفية باستخدام التقنيات الرقمية. أختص ببرنامج Exocad وحلول طب الأسنان الحديثة مع التركيز على الدقة ورضا المريض.",
    about_p2: "أنجزت أكثر من 2000 حالة وما زلت أطور مهاراتي من خلال التعلم المستمر والخبرة العملية.",
    about_training: "التدريب",
    about_edu: "والتعليم",
    quote_text: '"التصميم الجيد ليس فقط كيف يبدو، بل كيف يؤدي وظيفته ويصنع الفارق."',
    portfolio_title: "معرض الأعمال",
    portfolio_sub: "حالات مختارة من أعمالي في طب الأسنان الرقمي.",
    filter_all: "الكل",
    filter_ba: "قبل / بعد",
    filter_sd: "تصميم الابتسامة",
    filter_ven: "فينير",
    filter_wax: "واكس أب",
    btn_more_cases: "رؤية المزيد من الحالات ←",
    services_title: "خدماتي",
    services_sub: "حلول رقمية لابتسامات أفضل.",
    srv_smile_desc: "تصميم ابتسامة رقمي لنتائج طبيعية وجمالية.",
    srv_exocad_title: "تصميم Exocad",
    srv_exocad_desc: "منظومة عمل رقمية كاملة باستخدام Exocad.",
    srv_wax_desc: "تصميم واكس أب جمالي ووظيفي.",
    srv_ven_title: "تصميم الفينير",
    srv_ven_desc: "عدسات مخصصة لابتسامة مثالية.",
    srv_imp_desc: "تخطيط الزراعة والأدلة الجراحية الرقمية.",
    srv_arch_title: "الفك الكامل",
    srv_arch_desc: "تصميم رقمي لإعادة تأهيل الفك الكامل.",
    contact_title: "تواصل معي",
    contact_sub: "لنعمل معاً على إنجاز شيء رائع.",
    chat_me: "تحدث معي",
    send_email: "إرسال بريد",
    social_media: "وسائل التواصل",
    form_name: "الاسم",
    form_email: "البريد الإلكتروني",
    form_msg: "الرسالة",
    form_send: "إرسال الرسالة ←"
  },
  fr: {
    nav_home: "Accueil",
    nav_about: "À propos",
    nav_skills: "Pourquoi Nous",
    nav_services: "Services",
    nav_portfolio: "Portfolio",
    nav_contact: "Contact",
    btn_contact: "Contactez-moi",
    hero_subtitle: "DESIGNER DENTAIRE NUMÉRIQUE",
    hero_tagline: "Transformer les Sourires en Réalité Numérique",
    hero_desc: "Je crée des designs de sourire numériques précis et esthétiques à l'aide d'Exocad et d'outils modernes.",
    btn_view_work: "Voir mes travaux →",
    stat_cases: "Cas Réalisés",
    stat_certified: "Certifié",
    stat_digital_title: "Dentisterie Numérique",
    stat_passionate: "Passionné",
    featured_title: "Travaux En Vedette",
    featured_sub: "Vrais cas. Vrais résultats.",
    case_full_mouth: "Réhabilitation Buccale Complète",
    case_smile_design: "Design du Sourire",
    case_veneers: "Facettes / Veneers",
    case_waxup: "Wax-up Numérique",
    case_implant: "Design d'Implants",
    case_anterior: "Restauration Antérieure",
    btn_all_cases: "Voir Tous Les Cas →",
    why_title: "Pourquoi Travailler Avec Moi?",
    why_acc_title: "Précision",
    why_acc_desc: "Précision dans chaque détail du flux numérique.",
    why_aes_title: "Résultats Esthétiques",
    why_aes_desc: "Des sourires naturels et fonctionnels.",
    why_tool_title: "Outils Modernes",
    why_tool_desc: "Exocad et technologies numériques avancées.",
    why_time_title: "Respect des Délais",
    why_time_desc: "Engagé envers la qualité et les délais.",
    about_title: "À Propos de Moi",
    about_sub: "Apprenez à me connaître",
    about_role: "Designer Dentaire Numérique | Formateur",
    about_p1: "Je suis un designer dentaire numérique passionné par la création de sourires fonctionnels et esthétiques. Je suis spécialisé dans Exocad et la dentisterie numérique moderne.",
    about_p2: "J'ai réalisé plus de 2000 cas et je continue d'améliorer mes compétences.",
    about_training: "Formation",
    about_edu: "& Éducation",
    quote_text: '"Un bon design ne concerne pas seulement l\'apparence, mais aussi le fonctionnement."',
    portfolio_title: "Mon Portfolio",
    portfolio_sub: "Une sélection de mes cas de dentisterie numérique.",
    filter_all: "Tous",
    filter_ba: "Avant / Après",
    filter_sd: "Design Sourire",
    filter_ven: "Facettes",
    filter_wax: "Wax-up",
    btn_more_cases: "Voir Plus De Cas →",
    services_title: "Mes Services",
    services_sub: "Solutions numériques pour de meilleurs sourires.",
    srv_smile_desc: "Design de sourire numérique naturel et esthétique.",
    srv_exocad_title: "Design Exocad",
    srv_exocad_desc: "Flux de travail numérique complet sous Exocad.",
    srv_wax_desc: "Conception de wax-up esthétique et fonctionnel.",
    srv_ven_title: "Design de Facettes",
    srv_ven_desc: "Facettes personnalisées pour des sourires parfaits.",
    srv_imp_desc: "Planification d'implants et guides chirurgicaux.",
    srv_arch_title: "Arcade Complète",
    srv_arch_desc: "Conception numérique pour réhabilitation complète.",
    contact_title: "Contactez-moi",
    contact_sub: "Créons quelque chose de grand ensemble.",
    chat_me: "Discuter avec moi",
    send_email: "Envoyer un e-mail",
    social_media: "Réseaux Sociaux",
    form_name: "Votre Nom",
    form_email: "Adresse Email",
    form_msg: "Message",
    form_send: "Envoyer le Message →"
  }
};

function changeLanguage(lang) {
  // 1. Change HTML Direction & Lang attribute
  document.documentElement.lang = lang;
  if (lang === 'ar') {
    document.documentElement.dir = 'rtl';
  } else {
    document.documentElement.dir = 'ltr';
  }

  // 2. Update Active Button State
  document.querySelectorAll('.lang-btn').forEach(btn => btn.classList.remove('active'));
  event.target.classList.add('active');

  // 3. Update Text Content using data-i18n
  const elements = document.querySelectorAll('[data-i18n]');
  elements.forEach(element => {
    const key = element.getAttribute('data-i18n');
    if (translations[lang] && translations[lang][key]) {
      element.innerText = translations[lang][key];
    }
  });
}
